name: pas_mobie_11pplg1_32
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  path: ^1.8.3
  http: ^1.1.0
  sqflite: ^2.4.1
  shared_preferences: ^2.2.2
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
